basePath: /api
definitions:
  controllers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  controllers.UserOutput:
    properties:
      active:
        type: boolean
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      role:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is Go API Boilerplate
  license:
    name: MIT
    url: https://github.com/yhagio/go_api_boilerplate/blob/master/LICENSE
  termsOfService: http://swagger.io/terms/
  title: Go API Boilerplate Swagger
  version: "1.0"
paths:
  /api/account/profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.UserOutput'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Get user info of the logged in user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
